# https://taskfile.dev

version: "3"

env:
  DSN: root:password@tcp(127.0.0.1:3309)/go_svelte_todos?parseTime=true

tasks:
  default:
    cmds:
      - go run .
  migrateStatus:
    cmds:
      - goose -dir migrations mysql $DSN status
  migrateUp:
    cmds:
      - goose -dir migrations mysql $DSN up
  migrateDown:
    cmds:
      - goose -dir migrations mysql $DSN down
  docs:
    cmds:
      - swag init --dir ./,./handlers
